stages:
  - sync
  - build
  - test

# ==========================================================
#                      STAGE SYNC
# ==========================================================
sync-github-repo:
  stage: sync
  image: alpine/git:latest
  script:
    - git remote add github https://github.com/LuisGReyesM/examenautomatizacion.git
    - git fetch github
    - git checkout main
    - git reset --hard github/main
  # Este job se ejecuta solo en la rama "main"
  only:
    - main

# ==========================================================
#                      STAGE BUILD
# ==========================================================
build-job:
  stage: build
  image: openjdk:11-jre-slim
  script:
    - echo "Compilando el proyecto..."
    - ./mvnw compile
  # Asegura que esta etapa espere a que la de sync termine
  needs:
    - sync-github-repo

# ==========================================================
#                       STAGE TEST
# ==========================================================
unit-test-job:
  stage: test
  image: openjdk:11-jre-slim
  script:
    - echo "Ejecutando pruebas unitarias..."
    - ./mvnw test
  # Estas etapas esperan a que la de build termine
  needs:
    - build-job

integration-test-job:
  stage: test
  image: openjdk:11-jre-slim
  script:
    - echo "Ejecutando pruebas de integración..."
    - ./mvnw verify
  needs:
    - build-job