name: Deployment Pipeline
# ================================
on:
  workflow_run:
    workflows: ["Java CI"]
    types:
      - completed
    branches:
      - ci-deploy


jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      CANARY_NAMESPACE: canary
      BLUE_NAMESPACE: blue
      GREEN_NAMESPACE: green

    steps:
      # ================================
      # STAGE: Checkout
      # ================================
      - uses: actions/checkout@v3

      # ================================
      # STAGE: Set up JDK
      # ================================
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # ================================
      # STAGE: Build JAR
      # ================================
      - name: Build JAR
        run: mvn -B package --file pom.xml

      # ================================
      # STAGE: Verify JAR
      # ================================
      - name: Verify JAR exists
        run: ls -l target/ExamenAutomatizacion-0.0.1-SNAPSHOT.jar

      # ================================
      # STAGE: Build Docker image
      # ================================
      - name: Build Docker image
        run: docker build -t examen-app:latest .

      # ================================
      # STAGE: Deploy Canary (real con Docker)
      # ================================
      - name: Deploy Canary
        run: |
          echo "Desplegando aplicación en contenedor Docker (Canary)"
          docker run -d -p 8080:8080 --name examen-canary examen-app:latest

      # ================================
      # STAGE: Run Acceptance Tests (reales contra Canary)
      # ===============================
      # ================================
      # STAGE: Run Acceptance Tests
      # ================================
      - name: Run Acceptance Tests
        run: |
          echo "Ejecutando Acceptance Tests directamente en GitHub Actions"

          # Levantar la aplicación en segundo plano
          java -jar target/ExamenAutomatizacion-0.0.1-SNAPSHOT.jar &
          APP_PID=$!
          echo "Aplicación iniciada con PID $APP_PID"

          # Esperar hasta que /actuator/health devuelva 200
          echo "Esperando que la aplicación esté lista..."
          for i in {1..30}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/actuator/health || true)
            if [ "$STATUS" -eq 200 ]; then
              echo "Aplicación lista!"
              break
            fi
            sleep 2
          done

          # Verificar al final si está lista
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/actuator/health || true)
          if [ "$STATUS" -ne 200 ]; then
            echo "Tests fallaron: /actuator/health no respondió con 200"
            kill $APP_PID
            exit 1
          fi

          echo "Tests OK"
          kill $APP_PID
          echo "Aplicación detenida tras pruebas"
      
      
      

      # ================================
      # STAGE: Deploy Green (simulado)
      # ================================
      - name: Deploy Green
        run: |
          echo "Simulando despliegue Green en namespace $GREEN_NAMESPACE"
          echo "Traffic switch simulado a Green"
          # Simulación rollback
          ROLLBACK=false
          if [ "$ROLLBACK" = true ]; then
            echo "Rollback activado: volviendo a Blue"
            exit 1
          fi

      # ================================
      # STAGE: Stop Canary container
      # ================================
      - name: Stop Canary
        if: always()
        run: docker rm -f examen-canary || true

      # ================================
      # STAGE: Notify
      # ================================
      - name: Notify Team
        run: |
          echo "Despliegue completado exitosamente o rollback realizado si fue necesario"
