name: Deployment Pipeline

on:
  workflow_run:
    workflows: ["Java CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      CANARY_NAMESPACE: canary
      BLUE_NAMESPACE: blue
      GREEN_NAMESPACE: green

    steps:
      # ================================
      # STAGE: Checkout
      # ================================
      - uses: actions/checkout@v3

      # ================================
      # STAGE: Set up JDK
      # ================================
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # ================================
      # STAGE: Build JAR
      # ================================
      - name: Build JAR
        run: mvn -B package --file pom.xml

      # ================================
      # STAGE: Verify JAR
      # ================================
      - name: Verify JAR exists
        run: ls -l target/ExamenAutomatizacion-0.0.1-SNAPSHOT.jar

      # ================================
      # STAGE: Deploy Canary (simulado)
      # ================================
      - name: Deploy Canary
        run: |
          echo "Simulando despliegue Canary en namespace $CANARY_NAMESPACE"
          echo "Aplicación desplegada en Canary"

      # ================================
      # STAGE: Run Acceptance Tests (simulado)
      # ================================
      - name: Run Acceptance Tests
        run: |
          echo "Ejecutando Acceptance Tests en Canary"
          TEST_STATUS="UP"
          if [ "$TEST_STATUS" = "UP" ]; then
            echo "Tests OK"
          else
            echo "Tests fallaron, abortando despliegue"
            exit 1
          fi

      # ================================
      # STAGE: Deploy Green (simulado)
      # ================================
      - name: Deploy Green
        run: |
          echo "Simulando despliegue Green en namespace $GREEN_NAMESPACE"
          echo "Traffic switch simulado a Green"
          # Simulación rollback
          ROLLBACK=false
          if [ "$ROLLBACK" = true ]; then
            echo "Rollback activado: volviendo a Blue"
            exit 1
          fi

      # ================================
      # STAGE: Notify
      # ================================
      - name: Notify Team
        run: |
          echo "Despliegue completado exitosamente o rollback realizado si fue necesario"
