name: Deployment Pipeline

on:
  workflow_run:
    workflows: ["Java CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      IMAGE_NAME: myapp
      VERSION: latest
      CANARY_NAMESPACE: canary
      BLUE_NAMESPACE: blue
      GREEN_NAMESPACE: green
    steps:
      # ================================
      # STAGE: Checkout
      # ================================
      - uses: actions/checkout@v3

      # ================================
      # STAGE: Set up Docker & kubectl
      # ================================
      - name: Set up Docker & kubectl
        uses: docker/setup-buildx-action@v2

      # ================================
      # STAGE: Build Docker Image
      # ================================
      - name: Build Docker Image
        run: |
          echo "Construyendo imagen Docker: $IMAGE_NAME:$VERSION"
          docker build -t $IMAGE_NAME:$VERSION .

      # ================================
      # STAGE: Deploy Canary
      # ================================
      - name: Deploy Canary
        run: |
          echo "Desplegando Canary en namespace $CANARY_NAMESPACE"
          docker run -d --name canary-$IMAGE_NAME -p 8081:8080 $IMAGE_NAME:$VERSION
          echo "Simulación de Canary lista"

      # ================================
      # STAGE: Run Acceptance Tests
      # ================================
      - name: Run Acceptance Tests
        run: |
          echo "Ejecutando Acceptance Tests en Canary"
          # Simulamos un test HTTP simple
          if curl -s http://localhost:8081/actuator/health | grep UP; then
            echo "Tests OK"
          else
            echo "Tests fallaron, abortando despliegue"
            exit 1
          fi

      # ================================
      # STAGE: Blue-Green Switch
      # ================================
      - name: Deploy Green
        run: |
          echo "Desplegando versión Green"
          docker run -d --name green-$IMAGE_NAME -p 8080:8080 $IMAGE_NAME:$VERSION
          echo "Traffic switch simulado a Green"
          # Simulación rollback
          # En caso de falla, se detendría Green y volvería Blue
          if false; then
            echo "Rollback activado: volviendo a Blue"
            docker stop green-$IMAGE_NAME
            exit 1
          fi

      # ================================
      # STAGE: Notify
      # ================================
      - name: Notify Team
        run: |
          echo "Despliegue completado exitosamente o rollback realizado si fue necesario"
