name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw compile

      - name: Run Unit Tests
        run: ./mvnw test

      - name: Run Integration Tests
        run: ./mvnw verify

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            target/surefire-reports/
            target/failsafe-reports/

      - name: Report Unit Tests
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Unit Tests
          path: target/surefire-reports/*.xml
          reporter: github-pr-check
          fail-on-error: true

      - name: Report Integration Tests
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Integration Tests
          path: target/failsafe-reports/*.xml
          reporter: github-pr-check
          fail-on-error: true
