name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B compile --file pom.xml

      - name: Run Unit Tests
        run: mvn -B test --file pom.xml

      - name: Run Integration Tests
        run: mvn -B verify --file pom.xml

      # Reporte Unit Tests
      - name: Report Unit Tests
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Unit Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit

      # Reporte Integration Tests
      - name: Report Integration Tests
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Integration Tests
          path: target/failsafe-reports/*.xml
          reporter: java-junit
