name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Clonar el repositorio
      - uses: actions/checkout@v3

      # Configurar JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Dar permisos al Maven Wrapper
      - name: Grant execute permission for Maven Wrapper
        run: chmod +x mvnw

      # Compilar el proyecto
      - name: Build with Maven
        run: ./mvnw compile

      # Ejecutar pruebas unitarias
      - name: Run Unit Tests
        run: ./mvnw test

      # Ejecutar pruebas de integración
      - name: Run Integration Tests
        run: ./mvnw verify

      # Subir los reports como artifacts
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            target/surefire-reports/
            target/failsafe-reports/

      # Generar check de resultados de Unit Tests
      - name: Report Unit Tests
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Unit Tests
          path: target/surefire-reports/*.xml
          reporter: junit
          fail-on-error: true

      # Generar check de resultados de Integration Tests
      - name: Report Integration Tests
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Integration Tests
          path: target/failsafe-reports/*.xml
          reporter: junit
          fail-on-error: true
