name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clonar el repositorio
      - uses: actions/checkout@v2

      # Configurar JDK
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Compilar el proyecto
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Ejecutar pruebas
      - name: Run tests
        run: mvn test

      # Generar reporte HTML
      - name: Generate HTML Report
        run: mvn site

      # Subir reporte como artefacto
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: junit-html-report
          path: target/site/surefire-report.html
